### PR TITLE
feat(improved-omniauth): add support for sameWindow and inAppBrowser omniauth flows

### LINKED ISSUE #90: ng-token-auth with Ionic Framework/Cordova
Hello! 

I'm using ng-token-auth + devise-token-auth for an app I'm working on, and it's working great for the browser version of my site. My auth flow uses twitter oauth. I'm attempting to use the same auth code for Ionic/Cordova on mobile, but am running into issues with the log-in flow: after hitting the omniauth callback, my app stays on the 'redirecting...' screen. 

I believe the issue is with the Cordova app window and the new window that is opened by ng-token-auth. I'm thinking that a solution would be to implement ng-token-auth with the InAppBrowser Cordova plugin, but wanted to check to see if anyone has run into something similar and/or has any ideas.

Any help would be greatly appreciated!

### PR DESCRIPTION
**Pull request by booleanbetrayal**
This provides a mechanism to select between `sameWindow` (new default), `newWindow` (old default), or `inAppBrowser` modes for OAuth. This should allow for improved OAuth flows for a variety of use-cases, as well as supporting Cordova / PhoneGap implementations.

see also: lynndylanhurley/devise_token_auth#323 for devise_token_auth back-end implementation

Closes #90, #141

### CODE REVIEW

**Comment by elhachimi** [comment]
Cool which release will include this pull request.

**Comment by booleanbetrayal** [comment]
@elhachimi - it's slated for 0.0.28, but you're more than welcome to pull it down via bower by pointing directly to the branch. ie - `"ng-token-auth": "git://github.com/lynndylanhurley/ng-token-auth.git#improved_omniauth_flow"`

**Comment by dtelaroli** [comment]
I used it, it works, but not persist the session in the ionic application.
Maybe the cookies/session it's not setted corretly.

Can you help me to solve it?

**Comment by dtelaroli** [comment]
@booleanbetrayal 

The log error
```
D/CordovaLog( 3506): file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 19387 : TypeError: Cannot read property 'config' of undefined
D/CordovaLog( 3506):     at file:///android_asset/www/lib/ng-token-auth/dist/ng-token-auth.js:750:25
D/CordovaLog( 3506):     at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11994:17)
D/CordovaLog( 3506):     at response (file:///android_asset/www/lib/ng-token-auth/dist/ng-token-auth.js:748:23)
D/CordovaLog( 3506):     at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20962:27)
D/CordovaLog( 3506):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20978:27
D/CordovaLog( 3506):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22178:28)
D/CordovaLog( 3506):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21994:31)
D/CordovaLog( 3506):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22282:24)
D/CordovaLog( 3506):     at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17439:47)
D/CordovaLog( 3506):     at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17629:7)
I/chromium( 3506): [INFO:CONSOLE(19387)] "TypeError: Cannot read property 'config' of undefined
I/chromium( 3506):     at file:///android_asset/www/lib/ng-token-auth/dist/ng-token-auth.js:750:25
I/chromium( 3506):     at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11994:17)
I/chromium( 3506):     at response (file:///android_asset/www/lib/ng-token-auth/dist/ng-token-auth.js:748:23)
I/chromium( 3506):     at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20962:27)
I/chromium( 3506):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20978:27
I/chromium( 3506):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22178:28)
I/chromium( 3506):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21994:31)
I/chromium( 3506):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22282:24)
I/chromium( 3506):     at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17439:47)
I/chromium( 3506):     at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17629:7)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (19387)
D/CordovaLog( 3506): file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 19387 : TypeError: Cannot call method 'join' of undefined
D/CordovaLog( 3506):     at file:///android_asset/www/js/interceptor.js:49:24
D/CordovaLog( 3506):     at Scope.$emit (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22423:33)
D/CordovaLog( 3506):     at self.error (file:///android_asset/www/js/controllers.js:195:14)
D/CordovaLog( 3506):     at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20962:27)
D/CordovaLog( 3506):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20978:27
D/CordovaLog( 3506):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22178:28)
D/CordovaLog( 3506):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21994:31)
D/CordovaLog( 3506):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22282:24)
D/CordovaLog( 3506):     at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17439:47)
D/CordovaLog( 3506):     at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17629:7)
I/chromium( 3506): [INFO:CONSOLE(19387)] "TypeError: Cannot call method 'join' of undefined
I/chromium( 3506):     at file:///android_asset/www/js/interceptor.js:49:24
I/chromium( 3506):     at Scope.$emit (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22423:33)
I/chromium( 3506):     at self.error (file:///android_asset/www/js/controllers.js:195:14)
I/chromium( 3506):     at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20962:27)
I/chromium( 3506):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20978:27
I/chromium( 3506):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22178:28)
I/chromium( 3506):     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21994:31)
I/chromium( 3506):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22282:24)
I/chromium( 3506):     at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17439:47)
I/chromium( 3506):     at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17629:7)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (19387)
```

**Pull request merged**
