### PR TITLE
Add createPopup function to config

### PR DESCRIPTION
**Pull request by merqlove**
Useful when we need custom case.
It can be based on provider (window size) or window specs.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
seems sane to me. would you mind squashing those commits @merqlove ?

**Comment by merqlove** [comment]
This patch is about custom popup window, for example if we need window with size 600x400

**Comment by booleanbetrayal** [comment]
i gotcha, but would you mind rebasing those commits and squashing them into a single commit? will make for cleaner history once it merges.

**Comment by merqlove** [comment]
Yeah, i can force it

**Comment by booleanbetrayal** [comment]
thanks @merqlove!

**Comment by merqlove** [comment]
@booleanbetrayal Also will be good if someone try renewed tests :) Maybe Travis

**Comment by merqlove** [comment]
Yeah, seem that it fails  test/test/unit/ng-token-auth/multiple-user-types.coffee
I can fix it in other PR

**Comment by booleanbetrayal** [comment]
Thanks @merqlove ... hard to run tests from my phone.  =]

**Pull request merged**
