### PR TITLE
Angular 1.5.8 support

### PR DESCRIPTION
**Pull request by irobayna**

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
thanks!

**Comment by salmanasiddiqui** [comment]
@booleanbetrayal the package available on bower is not updated correctly. That package still has following dependency:
`"angular": ">=1.4 <=1.5.3"`

**Comment by ahmadalfy** [comment]
So I can ignore the warning and for the use of the current package?

**Comment by angelxmoreno** [comment]
Well this is super useful

**Comment by booleanbetrayal** [comment]
I just relaxed the restriction in master to `>=1.4 <1.6.0`. Hopefully that resolves it.

**Pull request merged**
