### PR TITLE
adds session storage option

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@MatthewVita - rather than rename the localStorage check to `hasModernStorageSupport` checking both, we should have an independent check for `sessionStorage`. 

The reason being, calling `getItem` on `localStorage` will cause exceptions if `localStorage` is unavailable in Safari. In your implementation, the `hasModernStorageSupport` check could fall-through to `sessionStorage`, and then during the retrieval call, we still try to call `localStorage.getItem` and if that returns null it'd proceed. Only ... it'd blow up at that point. Make sense?

**Comment by MatthewVita** [comment]
@booleanbetrayal very good point. I'd be happy to make the change but first I'd like to explore the following:

Can we prove that it is possible for `sessionStorage` to be in place and `localStorage` to not be? Same question applies inversely, of course.

AFAIK, The Web Storage API defines two types of storage areas [0]. Perhaps we can conclude that the spec says that both `sessionStorage` and `localStorage` are required for a correct implementation of Web Storage API but browsers can provide overrides to disable one or the other?

[0] http://www.sitepoint.com/an-overview-of-the-web-storage-api/

**Comment by booleanbetrayal** [comment]
I wouldn't bother making assumptions about browser implementations @MatthewVita . I've seen too much deviance from expectation along those lines with the Storage API, particularly in iOS Safari. Better to just have the separate checks. Let me know when that lands and I'll merge it!

**Comment by MatthewVita** [comment]
Good call. How that `amend` look?

**Comment by booleanbetrayal** [comment]
looks great. thanks @MatthewVita !

**Pull request merged**
