### PR TITLE
Add validateOnPageLoad documentation

### PR DESCRIPTION
**Pull request by dmackerman**

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
thanks for this!

**Comment by dmackerman** [comment]
Anytime! Awesome library by the way, our integration has been seamless!

**Comment by booleanbetrayal** [comment]
Thanks! Good to hear!

**Comment by angelxmoreno** [comment]
My integration has been far from seamless, ROFL. Do not worry though, I have massive amounts of notes. My set-up is NodeJS + ExpressJS + PassportJS. I can't wait to make it work 100% and post my results. Thanks for the PR and supporting this amazing module.

**Pull request merged**
