### PR TITLE
Protect against null access of this.dfd

### PR DESCRIPTION
**Pull request by cayblood**
This PR avoids attempts to resolve this.dfd when it is null. We were experiencing this when trying to manually validate a token by calling invalidateTokens and setAuthHeaders.

### CODE REVIEW

**Comment by brantchoate** [comment]
+1

**Comment by bendangelo** [comment]
+1 Please merge this in.

**Comment by booleanbetrayal** [comment]
I'm not sure I understand the use case. Perhaps @cayblood can elaborate. That being said, this seems harmless enough.

**Comment by cayblood** [comment]
@booleanbetrayal We were mocking users by calling these methods directly, and having trouble due to baked-in assumptions about the validity of the dfd property.

**Pull request merged**
