### PR TITLE
Fix tests for createPopup

### PR DESCRIPTION
**Pull request by merqlove**
Hey,
Try it first. I don't have access to Sauce, so i can't check...

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
ironically, neither do I   =]

**Comment by lynndylanhurley** [comment]
@booleanbetrayal - I don't know what happened, but this guy now has control of the npm package:
https://www.npmjs.com/~dyaa

@dyaa - can I have my project back?

**Comment by booleanbetrayal** [comment]
Thanks @lynndylanhurley - tests should be all fixed as of 763997465b7269a1f6de21a45b1306db6e4d2ef7.

**Comment by lynndylanhurley** [comment]
That's great! Thx @booleanbetrayal :+1:

**Pull request merged**
