### PR TITLE
CommonJS package manager support

### PR DESCRIPTION
**Pull request by flaviogranero**
I'm trying to use ng-token-auth in a project that manages its modules using browserify. In order to be able to load this lib as a CommonJS module, we need a few changes I'm including in this pull request.

Let me know if you have any questions.

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
Hi @flaviogranero - thank you for sending this PR!

I'm all about merging this, but I'm having a hard time reviewing the changes because every single line is changed (I'm sure it's due to indentation).

Before I go through it line by line, is there a way to make a version of this PR that shows only the changes?

Thanks again!

**Comment by flaviogranero** [comment]
hi @lynndylanhurley, yes.. I was trying to put all the code inside a IIFE to make the code scope more secure, but sounds like git is not showing a good diff, so I removed this part of the change.

**Comment by lynndylanhurley** [comment]
Cool, thx @flaviogranero! If you push the IIFE as a separate PR, I'll merge that as well.

**Comment by lynndylanhurley** [comment]
And welcome new [contributor](https://github.com/lynndylanhurley/ng-token-auth#callouts) :8ball:

**Comment by flaviogranero** [comment]
:)

----------------------------------------------
  Flávio Granero Maltempe
  TowerCRM - CRM para imobiliárias
  http://towercrm.com.br

  Site: http://flaviogranero.com
  Twitter: http://twitter.com/flaviogranero
  LinkedIn: http://www.linkedin.com/in/flaviogranero
----------------------------------------------

On Mon, Mar 16, 2015 at 4:33 PM, Lynn Dylan Hurley <notifications@github.com

**Pull request merged**
