### PR TITLE
Allow Custom Storage Configurations

### PR DESCRIPTION
**Pull request by sgtpepper43**
The strings 'cookies' and 'localStorage' are still allowed, but instead of switching on the string for functionality, the string is replaced by an object upon initialization, and the current methods just call the matching methods on those objects. This allows a user to, instead of specifying a string, set the storage to an object that implements these methods, which allows them to store the auth data in literally any way imaginable.

### CODE REVIEW

**Comment by sgtpepper43** [comment]
Don't pull this request yet... I just realized I need to wrap everything in a `when()` so that the object can use promises, but so it won't be required at all.

**Comment by lynndylanhurley** [comment]
This is great @sgtpepper43, I think this may be an improvement over the current system. Let me know when it's ready and I'll review ASAP.

**Comment by sgtpepper43** [comment]
About halfway through I realize allowing users to have a custom storage object that used promises (like it was being stored using an $http call) would break the current functionality too much. You'd have to wrap so much stuff in so many `.then ->`'s that it eventually bubbles up to the api, which would break everyone's code. So this should be good as it is.

**Comment by booleanbetrayal** [comment]
@sgtpepper43 - I think that what this PR aims to achieve is a good improvement. Would you be able to take a bit of time to resolve the merge conflicts? Also, a rebase against master, flattening the commits would be awesome.  =]

**Comment by booleanbetrayal** [comment]
@sgtpepper43 - It'd also be great to get some new unit test coverage on this change. Please let me know if you have any questions!

**Comment by sgtpepper43** [comment]
Everything's rebased, squashed, deconflicted, and tested. The tests I added are pretty simple, they just call methods that in turn call the custom storage object. Any functionality besides the proper methods being called is in the hands of the developer making the custom storage object, so there's not much more to test. Since the test suite doesn't break we already know it works for the two default storage types.

**Comment by booleanbetrayal** [comment]
Perfect! Thanks @sgtpepper43 !

**Comment by booleanbetrayal** [comment]
@sgtpepper43 - running into issues in the dist JS when attempting to use the default `localStorage` or `cookies` provider. 

```
ReferenceError: $window is not defined
    at Object.configure.storage.localStorage.retrieveData
```

this cascades to the other services `ipCookie` etc if you just use `window.location`. Could you please take a look?

**Comment by booleanbetrayal** [comment]
Incoming fix

**Comment by sgtpepper43** [comment]
Do you think defining the defaults with the `$get` block would work? Though if that works, it would probably work to call the methods using `.apply` and passing in `this` as a parameter

**Comment by sgtpepper43** [comment]
Oh, nevermind, you've got it

**Comment by booleanbetrayal** [comment]
Tell me if you see any issues in this commit - https://github.com/lynndylanhurley/ng-token-auth/commit/5c46a21da7625549cc1c9b624f274fcdda31a6d0

**Comment by meinzeugde** [comment]
is there any change that in the future we're able to work with promises as a return value for the custom storage object?
e.g. with localForage:

```
...
storage: {
	persistData: function(key, value) {
		return localforage.setItem(key,value);
	},
	retrieveData: function(key) {
		return localforage.getItem(key);
	},
	deleteData: function(key) {
		return $userData.removeItem(key);
	}
},
...
```

**Comment by sgtpepper43** [comment]
I went down a crazy rabbit hole with this PR trying to implement promises. I don't remember what I found down there, and I dunno how much the codebase has changed since then, but it was either impossible or going to take a major overhaul. Or maybe it was just going to take more work than I was willing to do, I'm not sure.

**Comment by meinzeugde** [comment]
in the meantime i have build around the whole mechanism...i use localStorage for ng-token-auth and localForage for persisting data.
i have the following concept implemented within angular.module(...).run():

```
var authenticateUser = function(toState) {
	$auth.validateUser().then(function (success) {
		...
	}, function (error) {
		//prevent infinite loop
		if(toState.name != 'login') $state.go('login');
	});
};

var clearSession = function() {
	localforage.removeItem('auth_headers');
};

/* Persist auth_headers in database after login */
$rootScope.$on('auth:login-success', function (event, user) {
	localforage.setItem('auth_headers',$window.localStorage.getItem('auth_headers'));
	$state.go('backend');
});

/* Remove auth_headers from database after logout */
$rootScope.$on('auth:logout-success', function (event) {
	clearSession();
	$state.go('login');
});

$rootScope.$on('auth:logout-error', function(event) {
	clearSession();
	$state.go('login');
});

$rootScope.$on('auth:validation-error', function (event) {
	clearSession();
	$state.go('login');
});

$rootScope.$on('$stateChangeError', function (event) {
	$state.go('login');
});

/* This is the most important part! */
$rootScope.$on("$stateChangeStart",function(event, toState){
	if($window.localStorage.getItem('auth_headers') == 'undefined') {
		//if localStorage does not have auth_headers, get them from the app-database
		$q.all({
			authHeaders: localforage.getItem('auth_headers')
		}).then(function(response) {
			$window.localStorage.setItem('auth_headers',response.authHeaders);
        })
    } else {
		//if localStorage has auth_headers, directly authenticate user
		authenticateUser(toState);
    }
});
```

the important configuration settings for ng-token-auth within angular.module(...).config():

```
$authProvider.configure({
          storage: 'localStorage',		
          validateOnPageLoad: false,	//validation is handled manually
          forceValidateToken: false,	//
        });
```

**Comment by meinzeugde** [comment]
@sgtpepper43 i looked at your code and found at least on spelling error: https://github.com/sgtpepper43/ng-token-auth/blob/promises/dist/ng-token-auth.js#L235

i'll go with my workaround, since it just works ;)

**Pull request merged**
