### PR TITLE
Add feature for autologout when session has expired

### PR DESCRIPTION
**Pull request by askobara**
I'm not sure is it helpful for all, but this functional very important for my project

### CODE REVIEW

**Comment by askobara** [comment]
All tests pass locally, but Travis has failed with `ERROR [launcher.sauce]: Can not start chrome`

**Comment by lynndylanhurley** [comment]
Thanks @askobara - I'll review this and merge tonight!

**Comment by lynndylanhurley** [comment]
The code is merged, I'll push another release once tests are in place.

I just added you to the [contributors list](https://github.com/lynndylanhurley/ng-token-auth#callouts). Thanks again :+1:

**Comment by askobara** [comment]
I made very stupid mistake in my PR, sorry for that, it was in a hurry :(
No need to divide on 1000 for timeout

**Comment by sebfie** [comment]
Any one can remove this divide by 1000? Thx

**Comment by booleanbetrayal** [comment]
@sebfie - see also: 30aba0986ef976fb8371bef4d9182e071fe186fe

**Comment by sebfie** [comment]
Thank you

**Pull request merged**
