### PR TITLE
handle validate user case api down

### PR DESCRIPTION
**Pull request by elhachimi**

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Hey @elhachimi - what's the situation where data would not be returned? Are you using this in conjunction with devise_token_auth? A little bit of background would be great. We also need this branch to be rebased against master before it can be merged. Thanks in advance for any follow-up.

**Comment by elhachimi** [comment]
Hey @booleanbetrayal i'me using it with python-social-auth in a django-rest backend, and when the backend is down it returns no data so the front-end bugs while trying to retrieve data.error.

**Comment by booleanbetrayal** [comment]
@elhachimi - Seems reasonable. Do you mind rebasing against master and resolving the conflicts? Also, not to nitpick, but capitalizing the "No" in that return message would make it a bit more consistent, and it would be nice to get some test coverage on this use case. Please let me know if you have any questions. Thanks!

**Comment by elhachimi** [comment]
Hey  @booleanbetrayal rebased this branch against master

**Comment by elhachimi** [comment]
I'll open another pull request

**Pull request closed without merging**
