### PR TITLE
(disregard) implements session storage

### PR DESCRIPTION
**Pull request by MatthewVita**
Instead of `localStorage`, `sessionStorage` is more appropriate.

I smoke tested (successfully, but wasn't an all encompassing smoke test) and made sure the unit tests pass. I was unable to run the localhost:7777 app because it points to what appears to be a Heroku instance for the backend.

To the repository maintainers: please supply your feedback on this PR and code review as necessary. I really appreciate your work on this library!

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Thanks for this PR @MatthewVita ! Have you had a chance to try this out in an iOS Safari Private Browsing mode? I've seen some crazy irregularities with what client stores are available in that mode, in the past.

**Comment by MatthewVita** [comment]
@booleanbetrayal good point. I can borrow my wife's iPhone to test with but I have a feeling after reading some blogs and SO posts, this will always be the case with Safari private browsing mode, regardless of `localStorage` or `sessionStorage`. Both of these extend `Storage` (no really, open up dev tools and type in `Storage`).

So this PR really boils down to a philosophical issue: should ng-token-auth use `localStorage` or `sessionStorage`? Maybe support both? `sessionStorage` is deleted when a tab/window is closed. `localStorage` lasts indefinitely and is accessible from all tabs/windows. I've seen auth strategies use both. session is probably more secure.

Maybe I can adjust the PR to allow for both?

Thanks!

**Comment by booleanbetrayal** [comment]
so, ng-token-auth already has support for custom persistence stores (via the `storage` config option). it then has reasonable defaults for `cookies` and `localStorage` if providing the corresponding string instead of a custom store object.

Perhaps maybe the most sensible thing for now is to implement an additive change for a convenience entry point for sessionStorage-backed persistence, and then follow-up with a fairly exhaustive test for a new default?

**Comment by MatthewVita** [comment]
@booleanbetrayal this sounds like the right approach. Don't know what I was thinking with the whole "replace `localStorage` with `sessionStorage`". `sessionStorage` should be among the options (I'm thinking of how my online banking uses it... if a user opens a new window the session won't perserve when visiting the URL again... very useful for these kind of use cases).

**Comment by MatthewVita** [comment]
closing. see https://github.com/lynndylanhurley/ng-token-auth/issues/244

**Pull request closed without merging**
