### PR TITLE
Allow to specify domain for cookies 

### PR DESCRIPTION
**Pull request by airatshigapov**
I recently encountered an issue when I couldn't share my auth headers (stored in cookies) between subdomains of my app. 

Example:

If I sign in from `foo.example.com`, auth headers cookie will be stored for `foo.example.com` by default (and obviously I will need to sign in again if I visit `bar.example.com` or `example.com`) and there is no possibility to customize it (in my case I need to store cookie for `.example.com` instead).

BTW is there any other way to share cookies between subdomains? I'm not very familiar with ng-token-auth but couldn't find any examples of using it in that way.

Thank you!

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@airatshigapov - Totally sensible PR, but I'm leaning towards #138 as a more generalized solution to client token persistence that would allow for additional flexibility you need. Please take a look and let me know if you have any concerns. If not, I'll close this PR. Thanks!

**Comment by booleanbetrayal** [comment]
Closing in favor of #138 (merged)

**Comment by airatshigapov** [comment]
@booleanbetrayal Oh looks like I completely forgot about this one :) #138 makes a lot of sense, thanks for merging it!

**Comment by booleanbetrayal** [comment]
np!

**Pull request closed without merging**
