### PR TITLE
unhandled rejections fix in angular 1.6

### PR DESCRIPTION
**Pull request by MariuszHenn**
Angular 1.6 invoke an error when rejected promise are unhandled. 

In addition, there is no need to return anything in promise's resolve and rejection callbacks. `then` method that accept callback methods as parameters, returns promise. Therefore `$q.reject(resp)` is unneded and cause unhandled promise rejection error.

### CODE REVIEW

**Comment by dlanileonardo** [comment]
+1

**Comment by booleanbetrayal** [comment]
Agree this should go in, but I'm currently seeing 8 failed tests involving other possibly-unhandled rejection errors. They can most likely be fixed in the spec setup itself, but I can't merge this until they pass. You mind taking a look?

**Comment by MariuszHenn** [comment]
Now auth methods return HttpPromise instead of promise with a result of callback (resolve/reject) method. Test should be fine.

**Comment by ThiagoAnunciacao** [comment]
+1

**Comment by angelxmoreno** [comment]
where the failing tests ever addressed @MariuszHenn ?
if so, can we merge @booleanbetrayal ?

**Comment by MariuszHenn** [comment]
As You see in my last comment (4 Oct 2017), all test passes in my local build.

**Comment by booleanbetrayal** [comment]
Merged!

**Pull request merged**
